baseURL = ""
title = "Stritter"
languageCode = "en-us"
defaultContentLanguage = "en"
description = "Frederic Stritter is a Sound Artist that lives and works in Vienna."
theme_color = "#000000"
disableHugoGeneratorInject = true
paginate = 100

#[permalinks]
    #live = '/:year/:month/:day/'

[taxonomies]
    category = "categories"
    tag = "tags"

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

[author]
    email="tong@disktree.net"
    web = "https://disktree.net"
