baseURL = ""
title = "stritter.audio"
languageCode = "en-us"
defaultContentLanguage = "en"
description = "This is some description"
keywords = ["stritter","audio","artist"]
theme_color = "#000000"

disableHugoGeneratorInject = true

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    description = " "
    customCSS = []
    customJS  = []
    author = {  fullname = "frederic stritter", name = "stritter", email = "frederic@stritter.audio" }
    email = "frederic@stritter.audio"
    publisher = ""

[menu]
    [[menu.main]]
        identifier = "home"
        name = "stritter"
        url = "/"
        weight = -100
     [[menu.main]]
        identifier = "audio" 
        name = "/audio"
        url = "/audio"
        weight = -99
    [[menu.main]]
        identifier = "live"
        name = "/live"
        url = "/live"
        weight = -98

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
      priority = 0.5
