baseURL = ""
title = "stritter.audio"
languageCode = "en-us"
defaultContentLanguage = "en"
description = "Frederic Stritter is a Sound Artist that lives and works in Vienna."
keywords =  ["velak","verein","akustik","musik","events"]
theme_color = "#000000"

disableHugoGeneratorInject = true
enableGitInfo = true
paginate = 1000
rssLimit = 100

#[permalinks]
    #live = '/:year/:month/:day/'

[taxonomies]
    tag = "tags"

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

