baseURL = ""
title = "stritter.audio"
languageCode = "en-us"
defaultContentLanguage = "en"
description = "This is some description"
keywords = ["stritter","audio","artist"]
theme_color = "#000000"

disableHugoGeneratorInject = true

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    description = " "
    customCSS = []
    customJS  = []
    author = {  fullname = "Frederic Stritter", name = "Stritter", email = "frederic@stritter.audio" }
    email = "frederic@stritter.audio"
    publisher = ""

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
      priority = 0.5
