baseURL = ""
title = "Stritter"
languageCode = "en-us"
defaultContentLanguage = "en"

disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true
paginate = 1000
rssLimit = 100


#[permalinks]
    #live = '/:year/:month/:day/'

[taxonomies]
    tag = "tags"

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

