description = "Frederic Stritter is a Sound Artist that lives and works in Vienna."
keywords = ["stritter","audio","artist"]
images = ['feature.jpg']
theme_color = "#000000"
author = { fullname = "Frederic Stritter", firstname = "Frederic", lastname = "Stritter", name = "Stritter", email = "frederic@stritter.audio" }
email = "frederic@stritter.audio"
publisher = "frederic@stritter.audio"
customCSS = []
customJS  = []

repository = "https://github.com/disktree/stritter.audio/"

[contact]
    email = "frederic@stritter.audio"
    web = "https://stritter.audio"
    [contact.address]
        street = "Oesterleingasse 13/21"
        postal_code = "1150"
        city = "Vienna"
        country = "AT"

[social]
    soundcloud = "fredericstritter"
    twitter = "Frederi61418717"

[developer]
    email = "tong@disktree.net"
    url = "https://disktree.net"
