#!/bin/sh

usage() {
    echo -e "Usage: stritter <live>|<projects>\n" \
        "Options:\n   live  <new> []\n" \
        "project new <name>\tCreate new project\n"
        "list\tList all content\n"
}

while true; do
    case "$1" in
        list)
            hugo list all
            exit 0
            ;;
        sync)
            shift
            git pull
            ;;
        start)
            shift
            npm start
            ;;
        live)
            while true; do
                #echo "$1 $2 $3"
                case "$2" in
                    new)
                        datetime="$3"
                        shift
                        node node_modules/hugo-bin/cli.js new "live/$datetime.md"
                        exit 0
                        ;;
                    *)
                        echo "Unknonw command"
                        exit 1
                    ;;
                esac
            done
            ;;
        project)
            while true; do
                #echo "$1 $2 $3"
                case "$2" in
                    new)
                        name="$3"
                        shift
                        node node_modules/hugo-bin/cli.js new "project/$name/index.md"
                        exit 0
                        ;;
                    *)
                        echo "Unknonw command"
                        exit 1
                    ;;
                esac
            done
            ;;

        help)
            usage
            exit 0
            ;;
    *) break;;
    esac
done
