name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: "0.99.1"
      - name: Setup npm
        run: npm install
      #- name: Test
        #run: npm test
      - name: Build style
        run: npm run build:style
      - name: Build site
        run: npm run build:hugo
      #- name: Store
        #uses: actions/upload-artifact@v3
        #with:
          #name: stritter.audio
          #path: public
